export const exampleData = [
    {
        Name: "Jack Daniel's Old No. 7",
        Size: "750ml",
        Price: 24.99,
        Promo: "SALE",
        "Message1 Status": "Yes",
        "Message1 Contents": "Sale Price",
        "Message2 Status": "Yes",
        "Message2 Contents": "Limit 2 Per Customer",
        StoreName: "Pedro's Spirits",
        StoreNum: "431-3333-2222",
        StoreAddress: "123 Ocean Drive, Miami FL"
    },
    {
        Name: "Tito's Handmade Vodka",
        Size: "1.75L",
        Price: 32.99,
        Promo: "SALE",
        "Message1 Status": "Yes",
        "Message1 Contents": "Gluten Free",
        "Message2 Status": "Yes",
        "Message2 Contents": "#1 Best Seller",
        StoreName: "Pedro's Spirits",
        StoreNum: "431-3333-2222",
        StoreAddress: "123 Ocean Drive, Miami FL"
    },
    {
        Name: "Casamigos Blanco Tequila",
        Size: "750ml",
        Price: 48.99,
        Promo: "SALE",
        "Message1 Status": "Yes",
        "Message1 Contents": "Staff Pick",
        "Message2 Status": "No",
        "Message2 Contents": "",
        StoreName: "Pedro's Spirits",
        StoreNum: "431-3333-2222",
        StoreAddress: "123 Ocean Drive, Miami FL"
    },
    {
        Name: "Kim Crawford Sauv Blanc",
        Size: "750ml",
        Price: 16.99,
        Promo: "SAVE $4",
        "Message1 Status": "Yes",
        "Message1 Contents": "Chilled Available",
        "Message2 Status": "Yes",
        "Message2 Contents": "New Zealand Import",
        StoreName: "Pedro's Spirits",
        StoreNum: "431-3333-2222",
        StoreAddress: "123 Ocean Drive, Miami FL"
    },
    {
        Name: "Captain Morgan Spiced",
        Size: "1L",
        Price: 21.99,
        Promo: "SAVE $1",
        "Message1 Status": "No",
        "Message1 Contents": "",
        "Message2 Status": "Yes",
        "Message2 Contents": "Great Mixer",
        StoreName: "Pedro's Spirits",
        StoreNum: "431-3333-2222",
        StoreAddress: "123 Ocean Drive, Miami FL"
    },
    {
        Name: "Bud Light Case (Cans)",
        Size: "24pk",
        Price: 26.99,
        Promo: "SAVE $2",
        "Message1 Status": "Yes",
        "Message1 Contents": "Coldest in Town",
        "Message2 Status": "Yes",
        "Message2 Contents": "Value Pack",
        StoreName: "Pedro's Spirits",
        StoreNum: "431-3333-2222",
        StoreAddress: "123 Ocean Drive, Miami FL"
    },
];
